In [1]:
import sys
sys.path.append('C:\\Users\\which\\work\\molecular-reaction-simulation-toolkit\\src\\MoREAT\\src')
import numpy as np
from structure import read_xyz_traj,write_xyz_file
from representation import generate_representation

In [2]:
system_list = read_xyz_traj('Al2F2_CCSDt_energy_MP2_force_training_set_initial.xyz')
print(len(system_list))

22390


In [ ]:
representaion_list = generate_representation(system_list).inverse_r_exp_r()
print(len(representaion_list))

In [60]:
def generate_landmarks(representaion_list, cutoff):
    '''
    This function selects landmarks based on the Cartesian distance between representations.
    The choice of cutoff depends on the representation.
    '''
    rep_index = np.array(range(len(representaion_list)))
    i = 0
    if_loop = True
    while if_loop:
        i_rep = representaion_list[rep_index[i]]
        distance = np.array([np.linalg.norm(i_rep - representaion_list[j]) for j in rep_index[i+1:] ])
        rep_index = np.delete(rep_index, np.where(distance < cutoff)[0]+i+1)
        i += 1
        if i >= len(rep_index):
            if_loop = False
        print('i=',i)
        print('index=',len(rep_index))
    return rep_index, representaion_list[rep_index]

In [66]:
rep_index, representaion_landmarks = generate_landmarks(representaion_list, cutoff=0.028)
print(len(rep_index))

i= 1
index= 21892
i= 2
index= 21684
i= 3
index= 21675
i= 4
index= 21674
i= 5
index= 21658
i= 6
index= 21499
i= 7
index= 21000
i= 8
index= 20681
i= 9
index= 20523
i= 10
index= 20498
i= 11
index= 20495
i= 12
index= 20126
i= 13
index= 20117
i= 14
index= 20079
i= 15
index= 19827
i= 16
index= 19782
i= 17
index= 19709
i= 18
index= 19679
i= 19
index= 19573
i= 20
index= 19478
i= 21
index= 19410
i= 22
index= 19269
i= 23
index= 19264
i= 24
index= 19254
i= 25
index= 19210
i= 26
index= 19096
i= 27
index= 18927
i= 28
index= 18896
i= 29
index= 18596
i= 30
index= 18556
i= 31
index= 18538
i= 32
index= 18529
i= 33
index= 18465
i= 34
index= 18204
i= 35
index= 18197
i= 36
index= 17822
i= 37
index= 17707
i= 38
index= 17616
i= 39
index= 17575
i= 40
index= 17367
i= 41
index= 17179
i= 42
index= 17089
i= 43
index= 16855
i= 44
index= 16799
i= 45
index= 16753
i= 46
index= 16440
i= 47
index= 16120
i= 48
index= 15861
i= 49
index= 15638
i= 50
index= 15473
i= 51
index= 15441
i= 52
index= 15393
i= 53
index= 15191
i=

In [67]:
print(len(representaion_list[rep_index]))

2354


In [68]:
train_index = np.sort(np.random.choice(rep_index,size=2239,replace=False))

In [69]:
new_system = []
for i in train_index:
    new_system.append(system_list[i])

In [70]:
write_xyz_file('Al2F2_CCSDt_energy_MP2_force_training_set_landmarks_2.xyz',new_system)

c:\Users\which\anaconda3\lib\site-packages\ase\io\extxyz.py:1000: UserWarning: write_xyz() overwriting array "forces" present in atoms.arrays with stored results from calculator
  warnings.warn('write_xyz() overwriting array "{0}" present '


In [78]:
z = np.array([[1,2],[3,4],[5,6],[7,8]])
print(z)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [38]:
i_sys = 10000
coef, basis, norm = generate_representation(system_list[i_sys]).forces_representation()
coef = coef[0]
basis = basis[0]
norm = norm[0]
force = system_list[i_sys].get_forces()

for i in range(4):
    print(force[i])
    print(np.sum([coef[i][j] * basis[i][j] / norm[i][j] for j in range(3)],axis=0))
    print('====================')

[ 0.00934519 -0.07812837 -0.01377474]
[ 0.05834445 -0.22096695 -0.00256259]
[-0.00938741  0.07825955  0.01376723]
[-0.0552273   0.22481787  0.00732309]
[ 0.4783544  -1.60554462  0.02465436]
[ 1.52393186 -4.77560225  0.22828229]
[-0.47831218  1.60541344 -0.02464685]
[-1.51265464  4.78183914 -0.2083905 ]


In [3]:
cartesian = generate_representation(system_list).Cartesian()

[array([ 0.       , -7.       ,  0.       ,  0.       , -7.       ,
         1.6687347,  0.       ,  7.       ,  1.6687347,  0.       ,
         7.       ,  0.       ]),
 array([ 2.31660600e-02, -6.99833769e+00,  6.69110000e-04,  3.30594000e-03,
        -6.97817564e+00,  1.68293568e+00, -8.32890000e-03,  7.01169065e+00,
         1.65842322e+00,  1.71565100e-02,  7.00500937e+00,  2.31359700e-02]),
 array([ 2.10620300e-02, -7.01021511e+00, -9.02949000e-03,  6.33130000e-03,
        -6.95914421e+00,  1.69390711e+00, -1.03348300e-02,  7.01484437e+00,
         1.64005790e+00,  1.99681300e-02,  6.99836735e+00,  5.20209200e-02]),
 array([ 0.01871962, -7.02335422, -0.018715  ,  0.00969925, -6.93808521,
         1.70455463, -0.01263818,  7.01838489,  1.62383199,  0.02319808,
         6.99094026,  0.07817282]),
 array([ 0.01604611, -7.03821357, -0.02799013,  0.01354311, -6.91425316,
         1.71419195, -0.01542346,  7.02253913,  1.61250556,  0.0271068 ,
         6.98231163,  0.09779384]),
 array

In [3]:
generate_representation(system_list[:5]).Cartesian()

[[ 0.        -7.         0.       ]
 [ 0.        -7.         1.6687347]
 [ 0.         7.         1.6687347]
 [ 0.         7.         0.       ]]
[0.         0.         0.83436735]
[[ 0.         -7.         -0.83436735]
 [ 0.         -7.          0.83436735]
 [ 0.          7.          0.83436735]
 [ 0.          7.         -0.83436735]]
[array([ 0.        , -7.        , -0.83436735,  0.        , -7.        ,
        0.83436735,  0.        ,  7.        ,  0.83436735,  0.        ,
        7.        , -0.83436735])]
[[ 2.31660600e-02 -6.99833769e+00  6.69110000e-04]
 [ 3.30594000e-03 -6.97817564e+00  1.68293568e+00]
 [-8.32890000e-03  7.01169065e+00  1.65842322e+00]
 [ 1.71565100e-02  7.00500937e+00  2.31359700e-02]]
[0.0088249  0.01004667 0.84129099]
[[ 1.43411575e-02 -7.00838436e+00 -8.40621885e-01]
 [-5.51896250e-03 -6.98822231e+00  8.41644685e-01]
 [-1.71538025e-02  7.00164398e+00  8.17132225e-01]
 [ 8.33160750e-03  6.99496270e+00 -8.18155025e-01]]
[array([ 0.        , -7.        , -0.8

[array([ 0.        , -7.        , -0.83436735,  0.        , -7.        ,
         0.83436735,  0.        ,  7.        ,  0.83436735,  0.        ,
         7.        , -0.83436735]),
 array([ 1.43411575e-02, -7.00838436e+00, -8.40621885e-01, -5.51896250e-03,
        -6.98822231e+00,  8.41644685e-01, -1.71538025e-02,  7.00164398e+00,
         8.17132225e-01,  8.33160750e-03,  6.99496270e+00, -8.18155025e-01]),
 array([ 1.18053725e-02, -7.02117821e+00, -8.53268600e-01, -2.92535750e-03,
        -6.97010731e+00,  8.49668000e-01, -1.95914875e-02,  7.00388127e+00,
         7.95818790e-01,  1.07114725e-02,  6.98740425e+00, -7.92218190e-01]),
 array([ 8.97492750e-03, -7.03532565e+00, -8.65676110e-01, -4.54425000e-05,
        -6.95005664e+00,  8.57593520e-01, -2.23828725e-02,  7.00641346e+00,
         7.76870880e-01,  1.34533875e-02,  6.97896883e+00, -7.68788290e-01]),
 array([ 5.72797000e-03, -7.05130958e+00, -8.77115435e-01,  3.22497000e-03,
        -6.92734917e+00,  8.65066645e-01, -2.5741600