In [1]:
import numpy as np

In [11]:
for _ in range(10):
    print(np.random.normal(size=3))

[-1.06572955  0.32176673  1.35846913]
[-0.35641824 -0.77744841 -0.74375016]
[-1.13999916  0.01881945  0.08500249]
[ 0.51410327  0.28107838 -0.80756578]
[ 0.65391389 -2.4352009  -0.339683  ]
[ 0.22108365  2.10562943 -1.0244937 ]
[ 1.59638845 -1.05691169 -1.45976392]
[ 0.18331838 -0.30141608 -1.74763951]
[-0.27144521 -0.87758495 -1.63294874]
[ 0.23804573 -1.58623699 -1.24398879]


In [12]:
z = np.random.normal(size=3)
print(z)

[ 0.20788179 -1.04018027 -0.22127085]


In [21]:
np.sign(23.233545)

1.0

In [15]:
z[1:]**2

array([1.081975  , 0.04896079])

In [ ]:
#this is step A
def position_update(x,v,dt):
    x_new = x + v*dt/2.
    return x_new

#this is step B
def velocity_update(v,F,dt):
    v_new = v + F*dt/2.
    return v_new

def random_velocity_update(v,gamma,kBT,dt):
    R = np.random.normal()
    c1 = np.exp(-gamma*dt)
    c2 = np.sqrt(1-c1*c1)*np.sqrt(kBT)
    v_new = c1*v + R*c2
    return v_new


def baoab(potential, max_time, dt, gamma, kBT, initial_position, initial_velocity,
                                        save_frequency=3, **kwargs ):
    x = initial_position
    v = initial_velocity
    t = 0
    step_number = 0
    positions = []
    velocities = []
    total_energies = []
    save_times = []
    
    while(t<max_time):
        
        # B
        potential_energy, force = potential(x,**kwargs)
        v = velocity_update(v,force,dt)
        
        #A
        x = position_update(x,v,dt)

        #O
        v = random_velocity_update(v,gamma,kBT,dt)
        
        #A
        x = position_update(x,v,dt)
        
        # B
        potential_energy, force = potential(x,**kwargs)
        v = velocity_update(v,force,dt)
        
        if step_number%save_frequency == 0 and step_number>0:
            e_total = .5*v*v + potential_energy

            positions.append(x)
            velocities.append(v)
            total_energies.append(e_total)
            save_times.append(t)
        
        t = t+dt
        step_number = step_number + 1
    
    return save_times, positions, velocities, total_energies   