In [1]:
import numpy as np
from ase.units import kB
import matplotlib.pyplot as plt

In [13]:
a = np.array([True, False, False])
print(a)
np.where(a == True, 1, 0)

[ True False False]


array([1, 0, 0])

In [11]:
np.sum(np.random.normal(size=1)[1:]**2)

0.0

T = [100]
i = 100
while i < 1000:
    i *= 1.2
    T.append(i)
T = np.array(T)

In [11]:
print(T)

[ 100.          120.          144.          172.8         207.36
  248.832       298.5984      358.31808     429.981696    515.9780352
  619.17364224  743.00837069  891.61004483 1069.93205379]


In [12]:
print(T[1:])
print(T[:-1])
delta = 1/(kB*T[1:]) - 1/(kB*T[:-1])
print(delta)
np.exp(delta)

[ 120.          144.          172.8         207.36        248.832
  298.5984      358.31808     429.981696    515.9780352   619.17364224
  743.00837069  891.61004483 1069.93205379]
[100.         120.         144.         172.8        207.36
 248.832      298.5984     358.31808    429.981696   515.9780352
 619.17364224 743.00837069 891.61004483]
[-19.3408701  -16.11739175 -13.43115979 -11.19263316  -9.3271943
  -7.77266192  -6.47721826  -5.39768189  -4.49806824  -3.7483902
  -3.1236585   -2.60304875  -2.16920729]


array([3.98443586e-09, 1.00070415e-07, 1.46866051e-06, 1.37753036e-05,
       8.89715146e-05, 4.21090865e-04, 1.53808328e-03, 4.52706303e-03,
       1.11304772e-02, 2.35556352e-02, 4.39959146e-02, 7.40474815e-02,
       1.14268162e-01])

In [21]:
np.sign(23.233545)

1.0

In [15]:
z[1:]**2

array([1.081975  , 0.04896079])

In [ ]:
#this is step A
def position_update(x,v,dt):
    x_new = x + v*dt/2.
    return x_new

#this is step B
def velocity_update(v,F,dt):
    v_new = v + F*dt/2.
    return v_new

def random_velocity_update(v,gamma,kBT,dt):
    R = np.random.normal()
    c1 = np.exp(-gamma*dt)
    c2 = np.sqrt(1-c1*c1)*np.sqrt(kBT)
    v_new = c1*v + R*c2
    return v_new


def baoab(potential, max_time, dt, gamma, kBT, initial_position, initial_velocity,
                                        save_frequency=3, **kwargs ):
    x = initial_position
    v = initial_velocity
    t = 0
    step_number = 0
    positions = []
    velocities = []
    total_energies = []
    save_times = []
    
    while(t<max_time):
        
        # B
        potential_energy, force = potential(x,**kwargs)
        v = velocity_update(v,force,dt)
        
        #A
        x = position_update(x,v,dt)

        #O
        v = random_velocity_update(v,gamma,kBT,dt)
        
        #A
        x = position_update(x,v,dt)
        
        # B
        potential_energy, force = potential(x,**kwargs)
        v = velocity_update(v,force,dt)
        
        if step_number%save_frequency == 0 and step_number>0:
            e_total = .5*v*v + potential_energy

            positions.append(x)
            velocities.append(v)
            total_energies.append(e_total)
            save_times.append(t)
        
        t = t+dt
        step_number = step_number + 1
    
    return save_times, positions, velocities, total_energies   