In [2]:
import numpy as np
import joblib
import ase.io

In [2]:
    def generate_Al2F2_representation(self, Al2F2):
        representation = []
        Al1 = Al2F2.get_positions()[0]
        F2 = Al2F2.get_positions()[1]
        Al3 = Al2F2.get_positions()[2]
        F4 = Al2F2.get_positions()[3]

        r_Al1_F2 = np.linalg.norm(Al1 - F2)
        r_Al3_F4 = np.linalg.norm(Al3 - F4)
        r_Al1_F4 = np.linalg.norm(Al1 - F4)
        r_Al3_F2 = np.linalg.norm(Al3 - F2)
        r_Al1_Al3 = np.linalg.norm(Al1 - Al3)
        r_F2_F4 = np.linalg.norm(F2 - F4)
        R = np.linalg.norm((Al1 + F2)/2 - (Al3 + F4)/2)

        representation.append(1.0/r_Al1_F2)
        representation.append(1.0/r_Al3_F4)
        representation.append(1.0/r_Al1_F4)
        representation.append(1.0/r_Al3_F2)
        representation.append(1.0/r_Al1_Al3)
        representation.append(1.0/r_F2_F4)
        representation.append(1.0/R)
        representation.append(np.exp(-r_Al1_F2))
        representation.append(np.exp(-r_Al3_F4))
        representation.append(np.exp(-r_Al1_F4))
        representation.append(np.exp(-r_Al3_F2))
        representation.append(np.exp(-r_Al1_Al3))
        representation.append(np.exp(-r_F2_F4))
        representation.append(np.exp(-R))

        return np.array(representation)

In [3]:
test = ase.io.read('MoREST.str', format='extxyz')
test

Atoms(symbols='AlF', pbc=False)

In [5]:
test.

RuntimeError: Atoms object has no calculator.

In [20]:
test.get_number_of_atoms()

C:\Users\which\anaconda3\lib\site-packages\ase\atoms.py:967: VisibleDeprecationWarning: Use get_global_number_of_atoms() instead
  warnings.warn('Use get_global_number_of_atoms() instead',


2

In [22]:
test.get_positions()

array([[0.1, 0.2, 0.3],
       [1.1, 1.2, 1.3]])

In [24]:
test.set_positions([[1.1, 2.3, 1.3], [0.1, 0.2, 0.3]])
test.get_positions()

array([[1.1, 2.3, 1.3],
       [0.1, 0.2, 0.3]])

In [25]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
for i, i_pos in enumerate(test.get_positions()):
    print(i)
    print(i_pos)

0
[1.1 2.3 1.3]
1
[0.1 0.2 0.3]


In [30]:
a = np.array(range(12))
print(a)
print(a.reshape(4,3))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
