### unit: eV, K, ps, Å, $\overset{\circ}{\text{A}}$

In [1]:
import os, sys
import numpy as np
sys.path.append('../read_parameters')
from read_parameters import read_parameters
sys.path.append('../enhanced_sampling')
from enhanced_sampling import enhanced_sampling
sys.path.append('../wall_potential')
from wall_potential import wall_potential

In [6]:
log_morest = open('MoREST.log','w')
MoREST_parameters = read_parameters.read_parameters(log_morest)

enhanced_sampling_parameters = MoREST_parameters.get_enhanced_sampling_parameters()
for key in enhanced_sampling_parameters:
    print(key+' : '+str(enhanced_sampling_parameters[key]))
if enhanced_sampling_parameters['enhanced_sampling']:
    its_parameters = MoREST_parameters.get_its_parameters()
    for key in its_parameters:
        print(key+' : '+str(its_parameters[key]))

wall_potential_parameters = MoREST_parameters.get_wall_potential_parameters()
for key in wall_potential_parameters:
    print(key+' : '+str(wall_potential_parameters[key]))
if wall_potential_parameters['wall_potential']:
    plane_wall_parameters = MoREST_parameters.get_plane_wall_parameters()
    for key in plane_wall_parameters:
        print(key+' : '+str(plane_wall_parameters[key]))

    
    
    

enhanced_sampling : True
enhanced_sampling_method : ITS
its_lower_bound_temperature : 700.0
its_upper_bound_temperature : 1000.0
its_number_of_replica : 5
its_replica_arrange : 0.0
its_trial_MD_steps : 100
its_delta_pk : 0.001
its_energy_shift : 0.0
its_replica_temperature : [ 700.          765.28557975  836.66002653  914.69121923 1000.        ]
its_replica_beta : [16.57788303 15.16364404 13.87005206 12.68681483 11.60451812]
its_initial_nk : [1.         0.24311055 0.06668128 0.02042352 0.00691982]
its_pk0 : [0.2 0.2 0.2 0.2 0.2]
wall_potential : True
collective_variable : False
wall_type : plane_opaque_wall
plane_wall_point : [2. 2. 2.]
plane_wall_normal_vector : [-0.18257419 -0.36514837 -0.91287093]
plane_wall_scaling : 1.0
plane_wall_scope : 3.0


In [7]:
simulation_temperature = 798 # K
simulation_maxsteps = 100000
time_step = 0.0001 # ps
#potential_energy = -20 # eV
#current_md_step = 1000
#md_force = np.array([[1.,2.,3.],[1.,3.,2.],[3.,1.,2.],[3.,2.,1.],[1.,2.,3.],[1.,3.,2.],[3.,1.,2.],[3.,2.,1.]])


current_md_step = 0
for _ in range(10):
    if _ == 0:
        if_initial = True
    else:
        if_initial = False
        
    potential_energy = np.random.random_sample()
    md_force = np.random.rand(2,3)
    current_md_step += 1
    print(md_force)
    #bias_force = enhanced_sampling.enhanced_sampling(enhanced_sampling_parameters['enhanced_sampling_method'],\
    #                                      if_initial, simulation_temperature, simulation_maxsteps,\
    #                                      time_step, potential_energy, current_md_step, md_force)
    #print(md_force,bias_force)
    
    wall_force = wall_potential.wall_potential(wall_potential_parameters['wall_type'],md_force)
    print(wall_force)

[[0.25350067 0.90268501 0.49583944]
 [0.30295741 0.02972184 0.35359443]]
[[-0.02140523 -0.04281047 -0.10702617]
 [-0.00818684 -0.01637368 -0.04093419]]
[[0.21667599 0.63665621 0.25941457]
 [0.79212053 0.87047412 0.78695448]]
[[-0.01108739 -0.02217479 -0.05543697]
 [-0.03999465 -0.0799893  -0.19997326]]
[[0.65942813 0.84862811 0.48321758]
 [0.06198215 0.78592965 0.33738296]]
[[-0.02316656 -0.04633312 -0.11583279]
 [-0.01378412 -0.02756824 -0.0689206 ]]
[[0.04114107 0.07694174 0.01571252]
 [0.29535059 0.10884551 0.14050112]]
[[-0.00186028 -0.00372057 -0.00930142]
 [-0.00477219 -0.00954439 -0.02386097]]
[[0.6387877  0.66127004 0.78568999]
 [0.72974871 0.01173563 0.7294615 ]]
[[-0.03329848 -0.06659697 -0.16649242]
 [-0.02042239 -0.04084478 -0.10211195]]
[[0.9113597  0.26230269 0.43144003]
 [0.01788936 0.45976337 0.08236751]]
[[-0.01529666 -0.03059332 -0.07648329]
 [-0.00523166 -0.01046331 -0.02615828]]
[[0.75219052 0.42850201 0.60919483]
 [0.68323718 0.8459048  0.74554301]]
[[-0.02227035 -