In [1]:
from read_parameters import read_parameters
from enhanced_sampling_ITS import its

In [6]:
__log_morest = open('MoREST.log','w')
MoREST_parameters = read_parameters(log_morest=__log_morest)
enhanced_sampling_parameters = MoREST_parameters.get_enhanced_sampling_parameters()
for key in enhanced_sampling_parameters:
    print(key+' : '+str(enhanced_sampling_parameters[key]))
if enhanced_sampling_parameters['enhanced_sampling']:
    its_parameters = MoREST_parameters.get_its_parameters()
    
zz=its()

enhanced_sampling : True
enhanced_sampling_method : ITS


In [7]:
zz.

In [6]:
zzz=1

In [7]:
if 'zzz' in dir():
    print(zzz)

1


In [3]:
from MoREST import morest
import numpy as np

test_morest = morest()

simulation_temperature = 798 # K
simulation_maxsteps = 100000
time_step = 0.0001 # ps
#potential_energy = -20 # eV
#current_md_step = 1000
potential_energy = 0.2
coordinate = np.array([[3.,1.,2.],[3.,2.,1.]])
md_force = np.array([[1.,2.,3.],[1.,3.,2.]])
#md_force = np.array([[1.,2.,3.],[1.,3.,2.],[3.,1.,2.],[3.,2.,1.],[1.,2.,3.],[1.,3.,2.],[3.,1.,2.],[3.,2.,1.]])


current_md_step = 0
for _ in range(100):
    if _ == 0:
        if_initial = True
    else:
        if_initial = False
        
    #potential_energy = np.random.random_sample()
    #md_force = np.random.rand(2,3)
    #coordinate = np.random.rand(2,3)
    current_md_step += 1
    print(coordinate)
    print('----')
    print(md_force)
    print('----')
    bias_force = test_morest.bias_sampling(simulation_temperature, simulation_maxsteps,\
                                          time_step, potential_energy, current_md_step, md_force, coordinate)
    print(bias_force)
    print('====')

[[3. 1. 2.]
 [3. 2. 1.]]
----
[[1. 2. 3.]
 [1. 3. 2.]]
----
[[1.09722354 2.19444708 2.40278174]
 [1.09722354 3.29167062 2.05555819]]
====
[[3. 1. 2.]
 [3. 2. 1.]]
----
[[1. 2. 3.]
 [1. 3. 2.]]
----
[[1.09722354 2.19444708 2.40278174]
 [1.09722354 3.29167062 2.05555819]]
====
[[3. 1. 2.]
 [3. 2. 1.]]
----
[[1. 2. 3.]
 [1. 3. 2.]]
----
[[1.09722354 2.19444708 2.40278174]
 [1.09722354 3.29167062 2.05555819]]
====
[[3. 1. 2.]
 [3. 2. 1.]]
----
[[1. 2. 3.]
 [1. 3. 2.]]
----
[[1.09722354 2.19444708 2.40278174]
 [1.09722354 3.29167062 2.05555819]]
====
[[3. 1. 2.]
 [3. 2. 1.]]
----
[[1. 2. 3.]
 [1. 3. 2.]]
----
[[1.09722354 2.19444708 2.40278174]
 [1.09722354 3.29167062 2.05555819]]
====
[[3. 1. 2.]
 [3. 2. 1.]]
----
[[1. 2. 3.]
 [1. 3. 2.]]
----
[[1.09722354 2.19444708 2.40278174]
 [1.09722354 3.29167062 2.05555819]]
====
[[3. 1. 2.]
 [3. 2. 1.]]
----
[[1. 2. 3.]
 [1. 3. 2.]]
----
[[1.09722354 2.19444708 2.40278174]
 [1.09722354 3.29167062 2.05555819]]
====
[[3. 1. 2.]
 [3. 2. 1.]]
----
[[1.