In [2]:
from ase import units
from scipy import constants
import numpy as np
from copy import deepcopy
from structure_io import read_xyz_file

In [5]:
constants.hbar

1.0545718176461565e-34

In [36]:
n_beads = 6
C_jk = np.zeros((n_beads,n_beads))
print(C_jk)
for k in range(n_beads):
    if k == 0:
        C_jk[:,k] = np.sqrt(1/n_beads)
    elif k > 0 and k <= (n_beads/2-1):
        for j in range(n_beads):
            C_jk[j,k] = np.sqrt(2/n_beads) * np.cos(2*units.pi*j*k/n_beads)
    elif k == n_beads/2:
        for j in range(n_beads):
            C_jk[j,k] = np.sqrt(1/n_beads)*(-1)**j
    elif k > n_beads/2:
        for j in range(n_beads):
            C_jk[j,k] = np.sqrt(2/n_beads)*np.sin(2*units.pi*j*k/n_beads)
print(C_jk)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[ 4.08248290e-01  5.77350269e-01  5.77350269e-01  4.08248290e-01
   0.00000000e+00  0.00000000e+00]
 [ 4.08248290e-01  2.88675135e-01 -2.88675135e-01 -4.08248290e-01
  -5.00000000e-01 -5.00000000e-01]
 [ 4.08248290e-01 -2.88675135e-01 -2.88675135e-01  4.08248290e-01
   5.00000000e-01 -5.00000000e-01]
 [ 4.08248290e-01 -5.77350269e-01  5.77350269e-01 -4.08248290e-01
  -2.82820064e-16  1.37910518e-15]
 [ 4.08248290e-01 -2.88675135e-01 -2.88675135e-01  4.08248290e-01
  -5.00000000e-01  5.00000000e-01]
 [ 4.08248290e-01  2.88675135e-01 -2.88675135e-01 -4.08248290e-01
   5.00000000e-01  5.00000000e-01]]


In [37]:
np.dot(C_jk.T,C_jk)

array([[ 1.00000000e+00, -1.04761073e-17,  1.75607620e-16,
        -9.95716912e-18,  2.04475515e-16,  6.35574357e-16],
       [-1.04761073e-17,  1.00000000e+00,  7.65661753e-17,
        -1.00546195e-16,  1.34484076e-16, -8.47541437e-16],
       [ 1.75607620e-16,  7.65661753e-17,  1.00000000e+00,
        -2.29519538e-17, -7.45106739e-16,  1.04183047e-15],
       [-9.95716912e-18, -1.00546195e-16, -2.29519538e-17,
         1.00000000e+00,  4.33902724e-16, -7.74352235e-16],
       [ 2.04475515e-16,  1.34484076e-16, -7.45106739e-16,
         4.33902724e-16,  1.00000000e+00,  2.49800181e-16],
       [ 6.35574357e-16, -8.47541437e-16,  1.04183047e-15,
        -7.74352235e-16,  2.49800181e-16,  1.00000000e+00]])

In [39]:
C_jk.T@C_jk

array([[ 1.00000000e+00, -1.04761073e-17,  1.75607620e-16,
        -9.95716912e-18,  2.04475515e-16,  6.35574357e-16],
       [-1.04761073e-17,  1.00000000e+00,  7.65661753e-17,
        -1.00546195e-16,  1.34484076e-16, -8.47541437e-16],
       [ 1.75607620e-16,  7.65661753e-17,  1.00000000e+00,
        -2.29519538e-17, -7.45106739e-16,  1.04183047e-15],
       [-9.95716912e-18, -1.00546195e-16, -2.29519538e-17,
         1.00000000e+00,  4.33902724e-16, -7.74352235e-16],
       [ 2.04475515e-16,  1.34484076e-16, -7.45106739e-16,
         4.33902724e-16,  1.00000000e+00,  2.49800181e-16],
       [ 6.35574357e-16, -8.47541437e-16,  1.04183047e-15,
        -7.74352235e-16,  2.49800181e-16,  1.00000000e+00]])

In [13]:
n = 3
beads = []
sys = read_xyz_file('MoREST_sampling.xyz')
for i in range(n):
    beads.append(deepcopy(sys))

In [14]:
for i in range(n):
    print(beads[i].get_pbc())

[False False False]
[False False False]
[False False False]


In [15]:
beads[0].set_pbc([True,True,True])

In [16]:
for i in range(n):
    print(beads[i].get_pbc())

[ True  True  True]
[ True  True  True]
[ True  True  True]


In [12]:
beads[0].get_pbc()

array([ True,  True,  True])