In [1]:
import numpy as np

In [47]:
v = np.array([[1,2,4],[6,4,7],[2,6,8],[8,7,2]])
print(v)

[[1 2 4]
 [6 4 7]
 [2 6 8]
 [8 7 2]]


In [48]:
w = v[[1,3]]
w *= 2
print(v)

[[1 2 4]
 [6 4 7]
 [2 6 8]
 [8 7 2]]


In [49]:
np.ones(4)

array([1., 1., 1., 1.])

In [9]:
np.linalg.norm(v,axis=-1)

array([ 4.58257569, 10.04987562, 10.19803903, 10.81665383])

In [14]:
m*np.linalg.norm(v,axis=-1)[:,np.newaxis]**2

array([[ 483.],
       [5454.],
       [7904.],
       [3276.]])

In [43]:
t = '1,2,3,4,5'

In [44]:
print(np.array(t.split(','),dtype='int'))

[1 2 3 4 5]


In [34]:
int(t)

ValueError: invalid literal for int() with base 10: 'all'

In [54]:
-np.ones(20)

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1.])

In [68]:
v = np.array([[1,2,4],[6,4,7],[2,6,8],[8,7,2]])
index = np.array([1,3])
z = np.ones(4)[:,np.newaxis]

In [69]:
for j, j_bias in enumerate(v[index]):
    print(z[index[j]])
    print(j_bias)
    z[index[j]] = j_bias
print(z)

ValueError: could not broadcast input array from shape (3,) into shape (1,)

In [72]:
print(z[0]*[1,2,3])

[1. 2. 3.]
