In [28]:
from ase import units
from scipy import constants
import numpy as np
from copy import deepcopy
from structure_io import read_xyz_file

In [29]:
constants.hbar

1.0545718176461565e-34

In [30]:
n_beads = 6
C_jk = np.zeros((n_beads,n_beads))
print(C_jk)
for k in range(n_beads):
    if k == 0:
        C_jk[:,k] = np.sqrt(1/n_beads)
    elif k > 0 and k <= (n_beads/2-1):
        for j in range(n_beads):
            C_jk[j,k] = np.sqrt(2/n_beads) * np.cos(2*units.pi*j*k/n_beads)
    elif k == n_beads/2:
        for j in range(n_beads):
            C_jk[j,k] = np.sqrt(1/n_beads)*(-1)**j
    elif k > n_beads/2:
        for j in range(n_beads):
            C_jk[j,k] = np.sqrt(2/n_beads)*np.sin(2*units.pi*j*k/n_beads)
print(C_jk)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[ 4.08248290e-01  5.77350269e-01  5.77350269e-01  4.08248290e-01
   0.00000000e+00  0.00000000e+00]
 [ 4.08248290e-01  2.88675135e-01 -2.88675135e-01 -4.08248290e-01
  -5.00000000e-01 -5.00000000e-01]
 [ 4.08248290e-01 -2.88675135e-01 -2.88675135e-01  4.08248290e-01
   5.00000000e-01 -5.00000000e-01]
 [ 4.08248290e-01 -5.77350269e-01  5.77350269e-01 -4.08248290e-01
  -2.82820064e-16  1.37910518e-15]
 [ 4.08248290e-01 -2.88675135e-01 -2.88675135e-01  4.08248290e-01
  -5.00000000e-01  5.00000000e-01]
 [ 4.08248290e-01  2.88675135e-01 -2.88675135e-01 -4.08248290e-01
   5.00000000e-01  5.00000000e-01]]


In [31]:
np.dot(C_jk.T,C_jk)

array([[ 1.00000000e+00, -1.04761073e-17,  1.75607620e-16,
        -9.95716912e-18,  2.04475515e-16,  6.35574357e-16],
       [-1.04761073e-17,  1.00000000e+00,  7.65661753e-17,
        -1.00546195e-16,  1.34484076e-16, -8.47541437e-16],
       [ 1.75607620e-16,  7.65661753e-17,  1.00000000e+00,
        -2.29519538e-17, -7.45106739e-16,  1.04183047e-15],
       [-9.95716912e-18, -1.00546195e-16, -2.29519538e-17,
         1.00000000e+00,  4.33902724e-16, -7.74352235e-16],
       [ 2.04475515e-16,  1.34484076e-16, -7.45106739e-16,
         4.33902724e-16,  1.00000000e+00,  2.49800181e-16],
       [ 6.35574357e-16, -8.47541437e-16,  1.04183047e-15,
        -7.74352235e-16,  2.49800181e-16,  1.00000000e+00]])

In [32]:
C_jk.T@C_jk

array([[ 1.00000000e+00, -1.04761073e-17,  1.75607620e-16,
        -9.95716912e-18,  2.04475515e-16,  6.35574357e-16],
       [-1.04761073e-17,  1.00000000e+00,  7.65661753e-17,
        -1.00546195e-16,  1.34484076e-16, -8.47541437e-16],
       [ 1.75607620e-16,  7.65661753e-17,  1.00000000e+00,
        -2.29519538e-17, -7.45106739e-16,  1.04183047e-15],
       [-9.95716912e-18, -1.00546195e-16, -2.29519538e-17,
         1.00000000e+00,  4.33902724e-16, -7.74352235e-16],
       [ 2.04475515e-16,  1.34484076e-16, -7.45106739e-16,
         4.33902724e-16,  1.00000000e+00,  2.49800181e-16],
       [ 6.35574357e-16, -8.47541437e-16,  1.04183047e-15,
        -7.74352235e-16,  2.49800181e-16,  1.00000000e+00]])

In [33]:
C_jk

array([[ 4.08248290e-01,  5.77350269e-01,  5.77350269e-01,
         4.08248290e-01,  0.00000000e+00,  0.00000000e+00],
       [ 4.08248290e-01,  2.88675135e-01, -2.88675135e-01,
        -4.08248290e-01, -5.00000000e-01, -5.00000000e-01],
       [ 4.08248290e-01, -2.88675135e-01, -2.88675135e-01,
         4.08248290e-01,  5.00000000e-01, -5.00000000e-01],
       [ 4.08248290e-01, -5.77350269e-01,  5.77350269e-01,
        -4.08248290e-01, -2.82820064e-16,  1.37910518e-15],
       [ 4.08248290e-01, -2.88675135e-01, -2.88675135e-01,
         4.08248290e-01, -5.00000000e-01,  5.00000000e-01],
       [ 4.08248290e-01,  2.88675135e-01, -2.88675135e-01,
        -4.08248290e-01,  5.00000000e-01,  5.00000000e-01]])

In [44]:
a = np.linspace(0,5,6)
print(a)
b = []
for i in a:
    b.append(i*np.array([[1,2,3]]))
b = np.array(b)
print(b)

[0. 1. 2. 3. 4. 5.]
[[[ 0.  0.  0.]]

 [[ 1.  2.  3.]]

 [[ 2.  4.  6.]]

 [[ 3.  6.  9.]]

 [[ 4.  8. 12.]]

 [[ 5. 10. 15.]]]


In [45]:
np.shape(b)

(6, 1, 3)

In [58]:
b

array([[[ 0.,  0.,  0.]],

       [[ 1.,  2.,  3.]],

       [[ 2.,  4.,  6.]],

       [[ 3.,  6.,  9.]],

       [[ 4.,  8., 12.]],

       [[ 5., 10., 15.]]])

In [56]:
b[:,0,:]

array([[ 0.,  0.,  0.],
       [ 1.,  2.,  3.],
       [ 2.,  4.,  6.],
       [ 3.,  6.,  9.],
       [ 4.,  8., 12.],
       [ 5., 10., 15.]])

In [60]:
C_jk[0]

array([0.40824829, 0.57735027, 0.57735027, 0.40824829, 0.        ,
       0.        ])

In [61]:
C_jk[:,0]

array([0.40824829, 0.40824829, 0.40824829, 0.40824829, 0.40824829,
       0.40824829])

In [63]:
[b[j,0,:]*C_jk[j,0] for j in range(6)]

[array([0., 0., 0.]),
 array([0.40824829, 0.81649658, 1.22474487]),
 array([0.81649658, 1.63299316, 2.44948974]),
 array([1.22474487, 2.44948974, 3.67423461]),
 array([1.63299316, 3.26598632, 4.89897949]),
 array([2.04124145, 4.0824829 , 6.12372436])]

In [73]:
b_k = np.array([[np.sum([b[j,i,:]*C_jk[j,k] for j in range(6)],axis=0) for i in range(1)] for k in range(6)])
print(b_k)

[[[ 6.12372436 12.24744871 18.37117307]]

 [[-1.73205081 -3.46410162 -5.19615242]]

 [[-1.73205081 -3.46410162 -5.19615242]]

 [[-1.22474487 -2.44948974 -3.67423461]]

 [[ 1.          2.          3.        ]]

 [[ 3.          6.          9.        ]]]


In [75]:
b_j = np.array([[np.sum([b_k[j,0,:]*C_jk[k,j] for j in range(6)],axis=0) for i in range(1)] for k in range(6)])
print(b_j)

[[[1.05471187e-15 2.10942375e-15 3.77475828e-15]]

 [[1.00000000e+00 2.00000000e+00 3.00000000e+00]]

 [[2.00000000e+00 4.00000000e+00 6.00000000e+00]]

 [[3.00000000e+00 6.00000000e+00 9.00000000e+00]]

 [[4.00000000e+00 8.00000000e+00 1.20000000e+01]]

 [[5.00000000e+00 1.00000000e+01 1.50000000e+01]]]


In [42]:
for i in range(len(6)):
    b[i]

[[ 6.12372436 12.24744871 18.37117307]
 [-1.73205081 -3.46410162 -5.19615242]
 [-1.73205081 -3.46410162 -5.19615242]
 [-1.22474487 -2.44948974 -3.67423461]
 [ 1.          2.          3.        ]
 [ 3.          6.          9.        ]]


In [43]:
C_jk.T@t

array([[ 2.2187796 ,  4.4375592 ,  6.6563388 ],
       [ 4.81999096,  9.63998191, 14.45997287],
       [ 2.67372659,  5.34745317,  8.02117976],
       [ 2.18350342,  4.36700684,  6.55051026],
       [ 1.        ,  2.        ,  3.        ],
       [ 3.73205081,  7.46410162, 11.19615242]])